### ISSUE TITLE
react native

### ISSUE THREAD

**Issue by askalburgi** [crubier/react-graph-vis#35]
Any desire to update this to work on react native? jsx etc

**Comment by crubier** [comment]
Unfortunately this project is based on Vis.js, a browser based visualization library.

This means that it would be impossible to port to react native simply.

In the mean time, a solution would be to include it in a webview in your react native app. I used this approach on some of my apps, and this works great, but it adds some complexity.

**Comment by crubier** [comment]
# Here is the solution to this

## 1 Make a web app that works even when loaded as a file

- Make a totally normal web application with webpack + react + react-graph-viz
- Make sure you `webpack.config.js` contains the following: `output: { publicPath: "./" }` so that your app is able to load from a relative file path.
- Make sure you use `HTMLWebpackPlugin` to generate an HTML file when you build your app.
- Test your web application on chrome **without http server or dev server**, just by opening the HTML file with chrome. You need to launch chrome with the `--allow-file-access-from-files` flag. See for example https://stackoverflow.com/questions/18586921/how-to-launch-html-using-chrome-at-allow-file-access-from-files-mode
- Check that you web app works as expected

## 2 Embed the web app in react native

- Add the `dist` files (HTML, JS, CSS, Images and so on) of your web app to your native app build.
- Load the local HTML file in your react native view: `<WebView source={require('./Policy.html')}/>` see for example https://stackoverflow.com/questions/42851296/react-native-load-local-html-file-into-webview
- Build your react native app
- Check that your react native app now includes a webview with your web app loaded in it

## 3 Enable two way communication between react native and the embedded react web

- Use https://github.com/R1ZZU/react-native-webview-messaging to communicate between your react native application and the react web application html embedded in the webview.
- Check that it works

**Comment by crubier** [comment]
I used this technique successfully to embed a fully functional instance of [Cesium.js](https://cesiumjs.org/) inside a React Native Ios App AND have bidirectional communication between react native and webview.

It is working right now, we build it every day at Sterblue in our CI pipeline.

**Comment by Arshiamidos** [comment]
hey guys  
found the trick base on [Image doesn't show after bundling into the apk](https://github.com/facebook/react-native/issues/4084).   
as you know **require('index.html')** work on _simulator_ and _emulator_ for both &driod and IOS  
but problem will faced when you bundle and you want release your app   
for android just follow this  **enablejavascript**  and copy you files in **assets** folder in `YOUR_APP/app/src/main/assets` and use just picture below.  

and for ios just bundle package with 
`react-native bundle --entry-file index.ios.js --platform ios --dev false --bundle-output ios/main.jsbundle --assets-dest ios`
when bundle created you have **main.bundle.js** and **asset** folder   
just copy you files in  **.xcworkspace** like this image  
![ios](https://user-images.githubusercontent.com/6451804/39201543-963c2e00-4804-11e8-9031-fb87a9f2c46e.jpg)
and set free all **refrence** in will be and unchanged just like mine. 
![screen shot - - at](https://user-images.githubusercontent.com/6451804/39201713-1260aeac-4805-11e8-92dd-efd9209cb44f.png)
i hope this tutorial help you from confusing release app in RN
